FROM localstack/localstack:4.0

# 1. Install only the absolute essentials
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    gnupg \
    wget

# 2. Manually add the HashiCorp GPG key and Repository
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep VERSION_CODENAME /etc/os-release | cut -d= -f2) main" | tee /etc/apt/sources.list.d/hashicorp.list

# 3. Install Terraform
RUN apt-get update && apt-get install -y terraform

# 4. Install tflocal
RUN pip install terraform-local

WORKDIR /docker-entrypoint-initaws.d