# Generated by Django 6.0.2 on 2026-04-01 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('is_grouped', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=10)),
                ('is_file_input', models.BooleanField(default=False)),
                ('is_weighted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_members', models.SmallIntegerField(default=4)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_points', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criterias', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Rubric Criteria',
                'verbose_name_plural': 'Rubric Criterias',
                'db_table': 'rubric_criteria',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('is_hidden', models.BooleanField(default=False)),
                ('expected_output', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupsMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='assignments.group')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='courses.roster')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'groupsmembership',
                'constraints': [models.UniqueConstraint(fields=('group', 'roster'), name='unique_membership', violation_error_message='This student is already a member of this group.')],
            },
        ),
    ]
