# Generated by Django 6.0.1 on 2026-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_points_allowed',
            field=models.IntegerField(default=100),
        ),
    ]
