# Generated by Django 6.0.1 on 2026-02-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_max_points_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_type',
        ),
    ]
