# Generated by Django 6.0.1 on 2026-02-16 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_testcase_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bucket', models.TextField()),
                ('key', models.TextField()),
            ],
            options={
                'db_table': 'test_file',
            },
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_input',
            field=models.ForeignKey(db_column='test_input_id', default=132, on_delete=django.db.models.deletion.PROTECT, related_name='input_test_cases', to='assignments.testfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_output',
            field=models.ForeignKey(db_column='test_output_id', default=123, on_delete=django.db.models.deletion.PROTECT, related_name='output_test_cases', to='assignments.testfile'),
            preserve_default=False,
        ),
    ]
