# Generated by Django 6.0.1 on 2026-02-16 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_testfile_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.OneToOneField(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='assignments.assignment'),
        ),
    ]
