# Generated by Django 6.0.1 on 2026-02-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_testcase_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.OneToOneField(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_input',
            field=models.ForeignKey(db_column='test_input_id', on_delete=django.db.models.deletion.PROTECT, related_name='input_test_case', to='assignments.testfile'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_output',
            field=models.ForeignKey(db_column='test_output_id', on_delete=django.db.models.deletion.PROTECT, related_name='output_test_case', to='assignments.testfile'),
        ),
    ]
