# Generated by Django 6.0.1 on 2026-02-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_submission_submitted_file_and_more'),
        ('assignments', '0008_alter_testcase_assignment_alter_testcase_test_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_input',
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_output_file',
            field=models.FileField(default=123, upload_to='test-cases/outputs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(default=123, upload_to='test-cases/inputs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='starter_code',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='TestFile',
        ),
    ]
