# Generated by Django 6.0.2 on 2026-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_remove_testcase_test_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='starter_code',
            field=models.FileField(blank=True, null=True, upload_to='starter-codes/'),
        ),
    ]
