# Generated by Django 6.0.2 on 2026-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_alter_assignment_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output_file',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_file',
        ),
        migrations.AddField(
            model_name='testcase',
            name='code_input',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
