# Generated by Django 6.0.2 on 2026-02-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_remove_testcase_expected_output_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='code_input',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='weight',
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_output_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment'),
        ),
        migrations.AlterModelTable(
            name='testcase',
            table=None,
        ),
    ]
