# Generated by Django 6.0.2 on 2026-02-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_remove_testcase_code_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='expected_output_file',
            new_name='expected_output',
        ),
    ]
