# Generated by Django 6.0.2 on 2026-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_rename_expected_output_file_testcase_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='points_possible',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
