# Generated by Django 6.0.2 on 2026-02-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_testcase_points_possible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input_file',
            new_name='input_text',
        ),
    ]
