# Generated by Django 6.0.2 on 2026-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_rename_input_file_testcase_input_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(default=300, help_text='Time limit in seconds'),
        ),
    ]
