# Generated by Django 6.0.2 on 2026-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_alter_testcase_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='starter_code',
            field=models.FileField(blank=True, null=True, upload_to='starter-code/'),
        ),
    ]
