# Generated by Django 6.0.2 on 2026-02-22 01:35

import apps.assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_alter_testcase_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(validators=[apps.assignments.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_points_allowed',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=255, validators=[apps.assignments.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='rubriccriteria',
            name='max_points',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rubriccriteria',
            name='name',
            field=models.CharField(max_length=100, validators=[apps.assignments.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='points_possible',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(help_text='Time limit in seconds', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
