# Generated by Django 6.0.2 on 2026-03-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_group_groupsmembership'),
        ('courses', '0007_course_grading_assistant_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsmembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rubriccriteria',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criterias', to='assignments.assignment'),
        ),
        migrations.AddConstraint(
            model_name='groupsmembership',
            constraint=models.UniqueConstraint(fields=('group', 'roster'), name='unique_membership', violation_error_message='This student is already a member of this group.'),
        ),
    ]
