# Generated by Django 6.0.2 on 2026-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_alter_groupsmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_file_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=10),
        ),
    ]
