# Generated by Django 6.0.2 on 2026-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_assignment_is_file_input_assignment_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubriccriteria',
            options={'verbose_name': 'Rubric Criteria', 'verbose_name_plural': 'Rubric Criterias'},
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='max_points',
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='desc_five',
            field=models.TextField(blank=True, help_text='Description for 5 points', null=True),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='desc_four',
            field=models.TextField(blank=True, help_text='Description for 4 points', null=True),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='desc_one',
            field=models.TextField(blank=True, help_text='Description for 1 point', null=True),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='desc_three',
            field=models.TextField(blank=True, help_text='Description for 3 points', null=True),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='desc_two',
            field=models.TextField(blank=True, help_text='Description for 2 points', null=True),
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
            preserve_default=False,
        ),
    ]
