# Generated by Django 6.0.2 on 2026-03-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_alter_rubriccriteria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_weighted',
            field=models.BooleanField(default=False),
        ),
    ]
