# Generated by Django 6.0.2 on 2026-03-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_assignment_is_weighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='max_points_allowed',
        ),
    ]
