# Generated by Django 6.0.2 on 2026-03-16 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_remove_assignment_max_points_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Test Case Input',
                'db_table': 'test_case_inputs',
            },
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='points_possible',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_cases',
        ),
        migrations.CreateModel(
            name='FileInputType',
            fields=[
                ('testcaseinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignments.testcaseinput')),
                ('file_url', models.FileField(upload_to='test_inputs/')),
            ],
            options={
                'db_table': 'file_input_types',
            },
            bases=('assignments.testcaseinput',),
        ),
        migrations.CreateModel(
            name='TextInputType',
            fields=[
                ('testcaseinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignments.testcaseinput')),
                ('input_text', models.TextField()),
            ],
            options={
                'db_table': 'text_input_types',
            },
            bases=('assignments.testcaseinput',),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_case_input',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='assignments.testcaseinput'),
            preserve_default=False,
        ),
    ]
