# Generated by Django 6.0.2 on 2026-03-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0024_testcaseinput_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccriteria',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment'),
        ),
    ]
