# Generated by Django 6.0.2 on 2026-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0025_alter_rubriccriteria_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_case_input',
        ),
        migrations.RemoveField(
            model_name='textinputtype',
            name='testcaseinput_ptr',
        ),
        migrations.AddField(
            model_name='testcase',
            name='file_input',
            field=models.FileField(blank=True, null=True, upload_to='test_cases/inputs/'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='text_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FileInputType',
        ),
        migrations.DeleteModel(
            name='TestCaseInput',
        ),
        migrations.DeleteModel(
            name='TextInputType',
        ),
    ]
