# Generated by Django 6.0.2 on 2026-03-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0026_remove_testcase_test_case_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='desc_five',
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='desc_four',
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='desc_one',
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='desc_three',
        ),
        migrations.RemoveField(
            model_name='rubriccriteria',
            name='desc_two',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='file_input',
        ),
        migrations.AddField(
            model_name='rubriccriteria',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
