x-backend-env: &backend-env
  DEBUG: ${DEBUG}
  ALLOWED_HOST: ${ALLOWED_HOST}
  ALLOWED_HOST_2: ${ALLOWED_HOST_2}
  ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
  POSTGRES_NAME: ${POSTGRES_NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SECRET_KEY: ${SECRET_KEY}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
  AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
  AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
  E2B_API_KEY: ${E2B_API_KEY}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}

services:

  redis:
    container_name: redis
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "6379:6379"

  backend:
    container_name: backend
    networks:
      - app-network
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level debug --access-logfile - --error-logfile -
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/admin/login/ || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
    environment: *backend-env

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: worker
    command: celery -A config worker --loglevel=info
    networks:
      - app-network
    environment: *backend-env
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started

  frontend:
    container_name: frontend
    networks:
      - app-network
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}

networks:
  app-network:
    driver: bridge

