# Generated by Django 6.0.1 on 2026-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_studentprofile_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
