# Generated by Django 6.0.1 on 2026-02-09 18:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_facultyprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
