# Generated by Django 6.0.1 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_facultyprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
