# Generated by Django 6.0.2 on 2026-02-22 01:35

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_facultyprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='title',
            field=models.CharField(max_length=255, validators=[apps.accounts.models.validate_title]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[apps.accounts.models.validate_major]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cwid',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[apps.accounts.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[apps.accounts.models.validate_name]),
        ),
    ]
