# Generated by Django 6.0.2 on 2026-02-28 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_facultyprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FA', 'Faculty'), ('ST', 'Student'), ('GA', 'Grading Assistant')], default='ST', max_length=2),
        ),
        migrations.CreateModel(
            name='GradingAssistantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Assistant Profile',
                'verbose_name_plural': 'Grading Assistant Profiles',
                'db_table': 'grading_assistant_profile',
            },
        ),
    ]
