# Generated by Django 6.0.2 on 2026-04-01 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_file', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed')], default='PENDING', max_length=50)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.group')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.roster')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'db_table': 'submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('optional_feedback', models.TextField(blank=True, null=True)),
                ('rubric_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_results', to='assignments.rubriccriteria')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_results', to='assessments.submission')),
            ],
            options={
                'verbose_name': 'Rubric Result',
                'verbose_name_plural': 'Rubric Results',
                'db_table': 'rubric_result',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'rubric_criteria'), name='unique_submission_rubric_criteria')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('exit_code', models.IntegerField(choices=[(0, 'Success'), (1, 'Failure')])),
                ('duration', models.FloatField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='assessments.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='assignments.testcase')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'db_table': 'test_result',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'test_case'), name='unique_submission_test_case')],
            },
        ),
    ]
