# Generated by Django 6.0.1 on 2026-02-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_rubricresult_options_alter_submission_options_and_more'),
        ('assignments', '0008_alter_testcase_assignment_alter_testcase_test_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='actual_output',
        ),
        migrations.AddField(
            model_name='testresult',
            name='output_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_file', to='assignments.testfile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_file', to='assignments.testfile'),
        ),
    ]
