# Generated by Django 6.0.1 on 2026-02-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_testresult_actual_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='output_file',
            field=models.FileField(default=123, upload_to='test-result/outputs/'),
            preserve_default=False,
        ),
    ]
