# Generated by Django 6.0.2 on 2026-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_submission_submitted_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubricresult',
            options={'verbose_name': 'Rubric Result', 'verbose_name_plural': 'Rubric Results'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='output_file',
            field=models.FileField(upload_to='test-results/'),
        ),
        migrations.AlterModelTable(
            name='rubricresult',
            table='rubric_result',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='submission',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='test_result',
        ),
    ]
