# Generated by Django 6.0.2 on 2026-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_rubricresult_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='output_file',
        ),
        migrations.AddField(
            model_name='testresult',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
