# Generated by Django 6.0.2 on 2026-02-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_testresult_output_file_testresult_output'),
        ('assignments', '0012_remove_testcase_code_input_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='execution_time_ms',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='error_message',
            new_name='stderr',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='output',
            new_name='stdout',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='status',
        ),
        migrations.AddField(
            model_name='testresult',
            name='exit_code',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Failure')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='assignments.testcase'),
        ),
        migrations.AlterModelTable(
            name='testresult',
            table=None,
        ),
    ]
