# Generated by Django 6.0.2 on 2026-02-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='points_earned',
        ),
    ]
