# Generated by Django 6.0.2 on 2026-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_remove_testresult_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
