# Generated by Django 6.0.2 on 2026-02-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_submission_status_alter_testresult_duration'),
        ('courses', '0006_alter_course_faculty_profile_alter_roster_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.roster'),
        ),
    ]
