# Generated by Django 6.0.2 on 2026-02-28 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_submission_roster'),
        ('assignments', '0018_group_groupsmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.group'),
        ),
        migrations.AlterField(
            model_name='rubricresult',
            name='rubric_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criterias', to='assignments.rubriccriteria'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
    ]
