# Generated by Django 6.0.2 on 2026-03-01 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_submission_group_alter_rubricresult_rubric_criteria_and_more'),
        ('assignments', '0018_group_groupsmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rubricresult',
            name='rubric_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_results', to='assignments.rubriccriteria'),
        ),
    ]
