# Generated by Django 6.0.2 on 2026-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_submission_created_at_submission_updated_at_and_more'),
        ('assignments', '0019_alter_groupsmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rubricresult',
            constraint=models.UniqueConstraint(fields=('submission', 'rubric_criteria'), name='unique_submission_rubric_criteria'),
        ),
    ]
