# Generated by Django 6.0.2 on 2026-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_rubricresult_unique_submission_rubric_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricresult',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='rubricresult',
            name='points',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
