# Generated by Django 6.0.2 on 2026-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_remove_rubricresult_points_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILE_ERROR', 'Compile Error')], default='PENDING', max_length=50),
        ),
    ]
