# Generated by Django 6.0.2 on 2026-03-18 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_alter_submission_status'),
        ('assignments', '0026_remove_testcase_test_case_input_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubricresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rubric Result', 'verbose_name_plural': 'Rubric Results'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.AddField(
            model_name='rubricresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubricresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('submission', 'test_case'), name='unique_submission_test_case'),
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='test_result',
        ),
    ]
