# Generated by Django 6.0.2 on 2026-03-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_alter_rubricresult_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricresult',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
