# Generated by Django 6.0.2 on 2026-03-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_submission_cross_class_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='ai_detection_details',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='ai_written_probability',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cross_class_issues',
        ),
    ]
