# Generated by Django 6.0.2 on 2026-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_remove_ai_cross_class_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cross_class_issues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
