# Generated by Django 5.0.2 on 2026-02-09 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0003_alter_course_crn_alter_course_description_roster'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_submitted', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='groups.group')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.roster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.FloatField()),
                ('optional_feedback', models.TextField(blank=True)),
                ('rubric_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.rubriccriteria')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_results', to='submissions.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('actual_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('points_earned', models.FloatField(default=0.0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='submissions.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.testcase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
