# Generated by Django 6.0.1 on 2026-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_facultyprofile_phone'),
        ('courses', '0004_roster'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('student_profile', 'course'), name='unique_student_course'),
        ),
    ]
