# Generated by Django 6.0.1 on 2026-02-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_facultyprofile_title'),
        ('courses', '0005_roster_unique_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='accounts.studentprofile'),
        ),
    ]
