# Generated by Django 6.0.2 on 2026-02-22 01:35

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_faculty_profile_alter_roster_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, validators=[apps.courses.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=50, validators=[apps.courses.models.validate_short_name]),
        ),
    ]
