# Generated by Django 6.0.2 on 2026-02-28 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role_gradingassistantprofile'),
        ('courses', '0006_alter_course_faculty_profile_alter_roster_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grading_assistant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.gradingassistantprofile'),
        ),
    ]
