# Generated by Django 6.0.1 on 2026-02-14 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_roster_unique_student_course'),
        ('groups', '0002_alter_groupmembership_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='GroupsMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='courses.roster')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'groupsmembership',
                'unique_together': {('group', 'roster')},
            },
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
