# Generated by Django 6.0.1 on 2026-02-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_testcase_test_type'),
        ('groups', '0003_remove_group_created_at_remove_group_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assignment'),
        ),
    ]
