# Generated by Django 6.0.1 on 2026-02-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='assignment',
        ),
    ]
